Team page
kossiitkgp/YAKW pull request #43
Opened 2023-07-25 06:58 UTC by Nafisay

2023-08-21 14:03 UTC, harshkhandeparkar requested changes

2023-08-21 14:03 UTC, harshkhandeparkar commented on src/components/TeamTab.astro
> +    // position: fixed;
Please remove these lines if they are no longer required.

2023-08-21 14:03 UTC, harshkhandeparkar commented on src/components/TeamTab.astro
> +    //@include raised;
Here too.

2023-08-21 14:03 UTC, harshkhandeparkar commented on src/components/TeamTab.astro
> +  .navbar-logo {
Rename these classes too, remove `navbar`.

2023-08-21 14:03 UTC, harshkhandeparkar commented on src/components/TeamTab.astro
> +  let toTop = document.querySelector('[href="#"]');
I believe this is no longer required.

2023-08-21 14:03 UTC, harshkhandeparkar commented on src/pages/team/[team].astro
> +    { params: { team: "Core Team Members" } },
```suggestion
    { params: { team: "ctm" } },
```
Rename the links here too.

2023-08-21 14:03 UTC, harshkhandeparkar commented on src/pages/team/[team].astro
> +    { params: { team: "Executives" } },
```suggestion
    { params: { team: "executives" } },
```

2023-08-21 14:03 UTC, harshkhandeparkar commented on src/pages/team/[team].astro
> +    { params: { team: "Advisors" } },
```suggestion
    { params: { team: "advisors" } },
```

2023-08-21 14:03 UTC, harshkhandeparkar commented on src/pages/team/[team].astro
> +if (team === "Core Team Members") {
```suggestion
if (team === "ctm") {
```

2023-08-21 14:03 UTC, harshkhandeparkar commented on src/pages/team/[team].astro
> +var team_members = ADVISORS;
```suggestion
let team_members = ADVISORS;
```

`var` is deprecated. See [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let) for more information.

2023-08-21 14:03 UTC, harshkhandeparkar commented on src/pages/team/[team].astro
> +if (team === "Executives") {
```suggestion
if (team === "executives") {
```

2023-08-21 14:03 UTC, harshkhandeparkar commented on src/pages/team/[team].astro
> +            team_members.map((advisor) => (
```suggestion
            team_members.map((member) => (
```
:)

2023-08-21 14:03 UTC, harshkhandeparkar commented on src/pages/team/[team].astro
> +    /*max-width: calc(100% - 2rem);
Remove these comments too, if they are not required.

2023-08-24 13:52 UTC, harshkhandeparkar requested changes

2023-08-24 13:52 UTC, harshkhandeparkar commented on src/components/TeamCard.astro
> +    z-index: -1;
```suggestion
```

2023-08-24 13:52 UTC, harshkhandeparkar commented on src/pages/team/[team].astro
> +let team_members = ADVISORS;
It would be better to use a switch...case statement here.

2023-08-24 13:52 UTC, harshkhandeparkar commented on src/components/TeamCard.astro
> +    <img src={`https://avatars.githubusercontent.com/${github_username}`} alt="PFP" class="pfp" />
If the `alt` property is set, let's set it to something useful like `Profile Picture` or `${name}'s Profile Picture`

2023-09-04 05:45 UTC, rajivharlalka requested changes
Moreover switching between CTM,EXec and Adv chages the entire page and goes back to top. Can this be corrected? @chirag-ghosh

2023-09-04 05:45 UTC, rajivharlalka commented on .yarn/releases/yarn-1.22.19.cjs
Is this needed?

2023-09-04 09:14 UTC, chirag-ghosh commented on .yarn/releases/yarn-1.22.19.cjs
For some reason, Nafisa ke system mai chahiye. I actually want to look into it and see what's the issue

2023-09-04 12:04 UTC, rajivharlalka commented
> I have now set it to automatically scroll down when we change the team. This however is not a good solution. Ideally, the component should update there itself. I think instead of using URLs, we can have a react component (to take advantage of reactive states) to achieve this. But let's keep it for sometime later.

@harshkhandeparkar  can you create an issue for this so that it doesnt get left out, Atleast we'll have soemthing working right now

2023-09-04 15:02 UTC, harshkhandeparkar reviewed
Should we make a separate tab for alumni?

2023-09-04 16:02 UTC, chirag-ghosh commented
You mean like the other 3? @rajivharlalka  and I thought to keep the alums section always present in the page. WHat do you think will be better?

2023-09-04 16:03 UTC, harshkhandeparkar commented
> You mean like the other 3? @rajivharlalka and I thought to keep the alums section always present in the page. WHat do you think will be better?

Since there are many alums, that section will be too long imo.

2023-09-05 15:32 UTC, chirag-ghosh approved these changes

2023-09-05 15:35 UTC, rajivharlalka approved these changes
LGTM since chirag reviewed

2023-09-05 15:36 UTC, harshkhandeparkar approved these changes
Who am I to suggest changes to Chirag

2023-09-05 15:36 UTC, chirag-ghosh commented
And there goes the flat heirarchy. Anyways....

2023-09-05 15:37 UTC, merged