Upcoming Events Section
kossiitkgp/YAKW pull request #47
Opened 2023-07-28 17:06 UTC by harshkhandeparkar

Closes #19 (hopefully)

2023-08-11 17:34 UTC, chirag-ghosh requested changes

2023-08-11 17:34 UTC, chirag-ghosh commented on src/components/EventCard.astro
> +    transition: all 300ms;
Add this to `.card-img` and `.reveal-on-hover` since they are also changing on hover.

2023-08-11 17:34 UTC, chirag-ghosh commented on src/components/EventCard.astro
> +  }
Styles for special cases like hover should be after the normal styles. again for better readability

2023-08-11 17:34 UTC, chirag-ghosh commented on src/data/events.json
will `events.json` file contain all events or only the upcoming ones?

going by the former like the filename suggests, we have to add some logic to show only the future events.

2023-08-11 17:34 UTC, chirag-ghosh commented on src/styles/index.scss
> +}
let's create a `mixins.scss` file for this.

2023-08-11 18:19 UTC, harshkhandeparkar commented on src/data/events.json
Added logic for that.

2023-08-11 21:16 UTC, chirag-ghosh commented on src/utils/events.ts
> +}
Better to create a types folder and have these there.

2023-08-12 08:58 UTC, chirag-ghosh approved these changes
Feels so good to finally merge this. Thanks Harsh.

2023-08-12 08:59 UTC, merged