Componentized the Code
kossiitkgp/YAKW pull request #59
Opened 2023-09-01 14:00 UTC by harshkhandeparkar

- Moved page sections into `sections/` from `components/`
- Created `Title` component
- Added `Title` and most styles directly to the `Section` component

2023-09-01 14:52 UTC, rajivharlalka commented
![image](https://github.com/kossiitkgp/YAKW/assets/68731551/e7925af9-fc65-4bbd-b207-f92a2fc733ad)
Looks the UI broke

2023-09-01 15:00 UTC, harshkhandeparkar commented
Fixed.

2023-09-01 17:28 UTC, harshkhandeparkar commented
> ![image](https://user-images.githubusercontent.com/68731551/265057859-d2706893-b493-4ac4-b3dd-c135b654091a.png) bottom is less

It is supposed to get fixed when the footer is added.

2023-09-02 13:25 UTC, rajivharlalka requested changes

2023-09-02 13:25 UTC, rajivharlalka commented on src/components/Section.astro
> +<style lang="scss"></style>
please remove this

2023-09-02 13:25 UTC, rajivharlalka commented on src/components/Section.astro
> +  titleAlignment?: string;
we dont need this

2023-09-02 13:25 UTC, rajivharlalka commented on src/sections/UpcomingEvents.astro
![image](https://github.com/kossiitkgp/YAKW/assets/68731551/486d1655-500d-4172-bd5e-3449b025dcdb)
let's fix this

2023-09-02 13:43 UTC, rajivharlalka approved these changes

2023-09-02 13:43 UTC, merged