Added css animation on 404 page
kossiitkgp/YAKW pull request #62
Opened 2023-09-05 11:35 UTC by YoganshSharma

2023-09-05 15:15 UTC, chirag-ghosh commented
![image](https://github.com/kossiitkgp/YAKW/assets/75582834/8addd3a4-37dc-4541-8377-9b504423391c)
seems to be some issue.

2023-09-05 15:38 UTC, rajivharlalka commented
@chirag-ghosh 
![image](https://github.com/kossiitkgp/YAKW/assets/68731551/e3021a5e-ad9a-44c5-b2b4-cdb8cd3cd101)

2023-09-05 15:38 UTC, rajivharlalka commented
[image: image.png]
@chiragghosh
Rajiv Harlalka,
Department of Mathematics
20MA20073,
Phone: +918987966604
Indian Institute of Technology, Kharagpur


On Tue, Sep 5, 2023 at 8:46 PM Chirag Ghosh ***@***.***>
wrote:

> [image: image]
> <https://user-images.githubusercontent.com/75582834/265745863-8addd3a4-37dc-4541-8377-9b504423391c.png>
> seems to be some issue.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kossiitkgp/YAKW/pull/62#issuecomment-1706818397>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQMMFH4LW736XAWUOF4YIVLXY463PANCNFSM6AAAAAA4LUM3YE>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-09-05 15:49 UTC, harshkhandeparkar requested changes

2023-09-05 15:49 UTC, harshkhandeparkar commented on src/pages/404.astro
> +    const step = (timestamp) => {
Please add some empty lines for readability :)

2023-09-05 16:03 UTC, chirag-ghosh requested changes

2023-09-05 16:04 UTC, chirag-ghosh commented on src/pages/404.astro
> +  };
Duplicate: https://github.com/kossiitkgp/YAKW/pull/62#discussion_r1316091823

2023-09-06 15:34 UTC, harshkhandeparkar approved these changes
LGTM

2023-09-19 09:23 UTC, harshkhandeparkar commented
Merging this because sukha sukha lag raha tha.

2023-09-19 09:23 UTC, merged